---
language: ruby
sudo: false
before_install: "gem update bundler"
script: "bundle exec rake testmetrics_parallel_rspec spec/"
rvm:
  - 2.5.1
matrix:
  fast_finish: true
notifications:
  email: false
